export enum CategoryEnum {
  FamilyLaw = 'FamilyLaw',
  CivilLaw = 'CivilLaw',
  CriminalLaw = 'CriminalLaw',
  Corporate = 'Corporate',
  Financial = 'Financial',
  Estate = 'Estate',
  MedicalAccident = 'MedicalAccident',
  Insurance = 'Insurance',
  AdministrativeProcessing = 'AdministrativeProcessing',
  SecurityProtection = 'SecurityProtection',
  Missing = 'Missing',
  Pet = 'Pet',
  IllegalDeviceDetection = 'IllegalDeviceDetection',
  DigitalInvestigation = 'DigitalInvestigation',
  InternationalInvestigation = 'InternationalInvestigation',
  FemaleDetective = 'FemaleDetective',
}
