server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: postgres_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: ./logs/postgres-log/*.log
  - job_name: app_info_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/app-log/info/*.log
  - job_name: app_error_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/app-log/error/*.log
