server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: postgres_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: ./logs/postgres-log/*.log

  # - job_name: postgres_log_info
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: postgres_info
  #         __path__: ./logs/postgres-log/info/*.log

  # - job_name: postgres_log_error
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: postgres_error
  #         __path__: ./logs/postgres-log/error/*.log

  # - job_name: postgres_log_debug
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: postgres_debug
  #         __path__: ./logs/postgres-log/debug/*.log
