export enum RegionEnum {
  Seoul = 'Seoul',
  Incheon = 'Incheon',
  Daejeon = 'Daejeon',
  Sejong = 'Sejong',
  Gwangju = 'Gwangju',
  Daegu = 'Daegu',
  Ulsan = 'Ulsan',
  Busan = 'Busan',
  Gyeonggi = 'Gyeonggi',
  Gangwon = 'Gangwon',
  Chungbuk = 'Chungbuk',
  Chungnam = 'Chungnam',
  Jeonbuk = 'Jeonbuk',
  Jeonnam = 'Jeonnam',
  Gyeongbuk = 'Gyeongbuk',
  Gyeongnam = 'Gyeongnam',
  Jeju = 'Jeju',
}
