export enum RegionEnum {
  SEOUL = 'seoul',
  INCHEON = 'incheon',
  DAEJEON = 'daejeon',
  SEJONG = 'sejong',
  GWANGJU = 'gwangju',
  DAEGU = 'daegu',
  ULSAN = 'ulsan',
  BUSAN = 'busan',
  GYEONGGI = 'gyeonggi',
  GANGWON = 'gangwon',
  CHUNGBUK = 'chungbuk',
  CHUNGNAM = 'chungnam',
  JEONBUK = 'jeonbuk',
  JEONNAM = 'jeonnam',
  GYEONGBUK = 'gyeongbuk',
  GYEONGNAM = 'gyeongnam',
  JEJU = 'jeju',
}
